services:
  backend:
    image: ssamantle-server
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: ssamantle-backend
    ports:
      - 44345:8000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://semantle:semantle@postgres:5432/semantle
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - volume-server:/app/data
  frontend:
    image: ssamantle-web-client
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        API_BASE_URL: http://localhost:44345
    container_name: ssamantle-frontend
    depends_on:
      - backend
    ports:
      - 80:80
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:latest
    ports: ["5432:5432"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U semantle"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes: ["volume-postgres:/var/lib/postgres/data"]
    environment:
      - POSTGRES_DB=semantle
      - POSTGRES_USER=semantle
      - POSTGRES_PASSWORD=semantle

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - volume-redis:/data
    command: [ "redis-server", "--appendonly", "yes" ]

volumes:
  volume-server:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/volume/server
  volume-redis:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/volume/redis
  volume-postgres:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/volume/postgres
